#######################################################
# Practice Config
# For info and help, check the Git repo over here:
# https://github.com/RoccoDev/Practice
# If you wish to contact me privately, send me an email:
# me@roccodev.pw
# You may also find me on Discord: RoccoDev#1337
# As well as on SpigotMC.org: Rocco
########################################################

########################################################
# DOCUMENTATION
#
# You can use color codes with '&' (e.g., &a).
#
# Some config entries support parameters:
# %1$s represents the first parameter,
# %2$s represents the second parameter,
# and so on.
#########################################################

## BOOLEANS

# Enable /report
bool.report: true

# Enable /ping
bool.ping: true

# Enable /duel
bool.duel: true


## PREFIXES

# Prefix for all information plugin messages
prefix.info: "&a&lPractice §8»§7 "

# Prefix for all error plugin messages
prefix.error: "&c&lPractice §8»§7 "


## ERRORS

# This error is thrown when the user is missing the required permission to do the action.
# Parameters:
# %1$s - The required permission (e.g., practice.report)
error.permission: "Invalid permissions. (Missing %1$s)"

# This error is thrown when the plugin could not find the player specified.
# Parameters:
# %1$s - The player name that couldn't be found
error.notfound: "Could not find player %1$s."

# This error is thrown when the player is kicked from an arena.
# Parameters:
# %1$s - The reason for the kick
error.arena.kick: "You have been kicked from the arena. Reason:&c %1$s"

## ARENA

# The Y coordinate of the arena (used by the generator).
# Too low y levels will cause the sky to appear dark,
# and too high y levels will cause the player models to disappear.
arena.ylevel: 60

# Whether the spectators should be able to fly.
arena.spectator.allowflight: true

# Whether the spectators should be flying as soon as they join/die.
arena.spectator.flyondeath: true


## /ping COMMAND

# The message that is sent as a result of the /ping command.
# Parameters:
# %1$s - The player
# %2$s - The player's ping, in milliseconds.
ping.result: "%1$s's ping is %2$sms."